### PR TITLE
Add a with keyword

### PR DESCRIPTION
**Pull request by perlancar**
The syntax is compatible with Moose's with.

This commit builds upon PR#6.

Tests can be added upon request.

### CODE REVIEW

**Comment by peczenyj** [comment]
How this PR is related to pull request #6 ?

**Comment by perlancar** [comment]
> How this PR is related to pull request #6 ?

I use the same fallback mechanism like in #6. So when the role is not parameterized (determined by whether the user specifies parameters or not, yes this is not ideal but anyways...), then the role can be added either using apply(), or if apply() is not available then using Moo::Role->add_roles_to_package or the Role::Tiny equivalent.

**Comment by perlancar** [comment]
BTW, the specific use case that I'm facing:

I have Role::Versioning::Scheme which is used by the other roles: Versioning::Scheme::Monotonic, Versioning::Scheme::Semantic, Versioning::Scheme::Perl. They are all Role::Tiny roles.

I want to add a new role Versioning::Scheme::CalVer (ref: https://calver.org/) as a separate Perl distribution, where I want to let role users specify the calendar pattern to use, e.g. YY.MM. This determines version normalizing, comparing, bumping. So Versioning::Scheme::CalVer will be a parameterized role. I don't want to have to switch to MooX::Role::Parameterized for the other already-written roles.

**Comment by peczenyj** [comment]
This was reimplemented on v0.100

**Pull request closed without merging**
